import { Text } from "./Text";
import { Heading } from "./Heading";
import { Img } from "./Img";
import { ReactTable } from "./ReactTable";
import { Input } from "./Input";
import { Button } from "./Button";
import { Slider } from "./Slider";
import { GoogleMap } from "./GoogleMap";
import { SelectBox } from "./SelectBox";
export { Text, Heading, Img, ReactTable, Input, Button, Slider, GoogleMap, SelectBox };
